// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa5MuJcwvl_c0pMaFU1W6-vrUlzS2Es_g',
    appId: '1:560762160958:web:2412f06a85117db1f00e6f',
    messagingSenderId: '560762160958',
    projectId: 'cotizador-dolar-api',
    authDomain: 'cotizador-dolar-api.firebaseapp.com',
    storageBucket: 'cotizador-dolar-api.firebasestorage.app',
    measurementId: 'G-V6K9SQ6YJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN216cdJHW2IMaAyEPFx1oe5fnMihiEMQ',
    appId: '1:560762160958:android:c2d84acade0ff2daf00e6f',
    messagingSenderId: '560762160958',
    projectId: 'cotizador-dolar-api',
    storageBucket: 'cotizador-dolar-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CQw3skXvDJjlVDSylGZ_dswdUSG7wFM',
    appId: '1:560762160958:ios:904e2d6043b15e91f00e6f',
    messagingSenderId: '560762160958',
    projectId: 'cotizador-dolar-api',
    storageBucket: 'cotizador-dolar-api.firebasestorage.app',
    iosBundleId: 'com.example.convertidorGustavo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CQw3skXvDJjlVDSylGZ_dswdUSG7wFM',
    appId: '1:560762160958:ios:904e2d6043b15e91f00e6f',
    messagingSenderId: '560762160958',
    projectId: 'cotizador-dolar-api',
    storageBucket: 'cotizador-dolar-api.firebasestorage.app',
    iosBundleId: 'com.example.convertidorGustavo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa5MuJcwvl_c0pMaFU1W6-vrUlzS2Es_g',
    appId: '1:560762160958:web:e387618ca6091a4ef00e6f',
    messagingSenderId: '560762160958',
    projectId: 'cotizador-dolar-api',
    authDomain: 'cotizador-dolar-api.firebaseapp.com',
    storageBucket: 'cotizador-dolar-api.firebasestorage.app',
    measurementId: 'G-6V9B0Q8C6S',
  );
}
